# Password-Generator 
# GUI.py
# Created by Mauro J. Pappaterra on 04 of November 2017.
import passwords as p

password = p.getPassword()

print ("This is a password randomly generated by choosing 4 random words from a dictionary of 10000 words")
print ("The entropy for any password generated using this method will be of " + p.getEntropy(10000))
print ("The password length necessary to generate a passwords of the same entropy, by randomly choosing characters, would be of:")

print ("In the set of characters [0-9]" + p.estimateLength(10, 44))
print ("In the set of characters [a-z] or [A-Z]" + p.estimateLength(26, 44))
print ("In the set of characters [a-z] and [A-Z]" + p.estimateLength(52, 44) )
print ("In the set of characters [a-z] and [A-Z] and [0-9]" + p.estimateLength(62, 44))