# Password-Generator 
# GUI.py
# Created by Mauro J. Pappaterra on 04 of November 2017.
import passwords as p

password = p.getPassword()

print ("This is a password randomly generated by choosing 4 random words from a dictionary of 10000 words")
print ("The entropy for any password generated using this method will be of " + p.getEntropy(10000))
print ("To generate passwords of the same entropy in different randomized single character sets would be of:")

print ("Characters [0-9]" + p.estimateLength(10, 44))
print ("Characters [a-z] or [A-Z]" + p.estimateLength(26, 44))
print ("Characters [a-z] and [A-Z]" + p.estimateLength(52, 44) )
print ("Characters [a-z] and [A-Z] and [0-9]" + p.estimateLength(62, 44))